/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import system.*;

/**
 *
 * @author David Enoma
 *
 */
public class InputResult extends javax.swing.JFrame {

    /**
     * Creates new form InputResult
     */
    Connection con;
    ConnectionS con_ = new ConnectionS();
    Statement stmnt;
    String sql = null;
    String sql2 = null;
    String[] subjects;
    PreparedStatement pStmnt;
    private int studentId;

    public InputResult() {

        initComponents();

    }

    void clearCounters() {
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField22.setText("");
        jTextField21.setText("");
        jTextField23.setText("");
        jTextField24.setText("");
        jTextField25.setText("");
        englishMidterm.setText("");
        mathematicsMidterm.setText("");
        scienceMidterm.setText("");
        socialMidterm.setText("");
        fineartMidterm.setText("");
        agricMidterm.setText("");
        crsMidterm.setText("");
        pheMidterm.setText("");
        introtechMidterm.setText("");
        homeeconsMidterm.setText("");
        businessMidterm.setText("");
        frenchMidterm.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        englishMidterm = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        mathematicsMidterm = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        scienceMidterm = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        socialMidterm = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        fineartMidterm = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        agricMidterm = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        crsMidterm = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        pheMidterm = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        introtechMidterm = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        homeeconsMidterm = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        businessMidterm = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        frenchMidterm = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INPUT RESULTS");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(134, 186, 210));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusableWindowState(false);
        setForeground(java.awt.Color.white);

        jDesktopPane1.setBackground(new java.awt.Color(134, 186, 210));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(134, 186, 210));

        jTable2.setBackground(new java.awt.Color(134, 186, 210));
        jTable2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STUDENT_ID", "LAST_NAME", "FIRST_NAME", "MIDDLE_NAME"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(134, 186, 210));
        jTable2.setRowHeight(20);
        jTable2.setSelectionBackground(new java.awt.Color(134, 186, 210));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        jTable2.getAccessibleContext().setAccessibleParent(jPanel1);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JSS1", "JSS2", "JSS3", "SSS1", "SSS2", "SSS3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016/2017", "2017/2018" }));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("Select the class before updating the results");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 640));
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(134, 186, 210));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField1.setText("Click Select");
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 254, -1));

        jTextField14.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField14.setText("0");
        jTextField14.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField14.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 40, 25));

        englishMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        englishMidterm.setText("0");
        englishMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(englishMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 40, 25));

        jTextField39.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField39.setText("0");
        jTextField39.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 40, 25));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField2.setText("Click Select");
        jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 254, -1));

        jTextField15.setBackground(new java.awt.Color(204, 204, 204));
        jTextField15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField15.setText("0");
        jTextField15.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField15.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 40, 25));

        mathematicsMidterm.setBackground(new java.awt.Color(204, 204, 204));
        mathematicsMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mathematicsMidterm.setText("0");
        mathematicsMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        mathematicsMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        mathematicsMidterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathematicsMidtermActionPerformed(evt);
            }
        });
        jPanel2.add(mathematicsMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 40, 25));

        jTextField40.setBackground(new java.awt.Color(204, 204, 204));
        jTextField40.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField40.setText("0");
        jPanel2.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 40, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField3.setText("Click Select");
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 254, -1));

        jTextField16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField16.setText("0");
        jTextField16.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField16.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 40, 25));

        scienceMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        scienceMidterm.setText("0");
        scienceMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        scienceMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(scienceMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 40, 25));

        jTextField41.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField41.setText("0");
        jPanel2.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 40, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField4.setText("Click Select");
        jTextField4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField4.setEnabled(false);
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 254, -1));

        jTextField17.setBackground(new java.awt.Color(204, 204, 204));
        jTextField17.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField17.setText("0");
        jTextField17.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField17.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 40, 25));

        socialMidterm.setBackground(new java.awt.Color(204, 204, 204));
        socialMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        socialMidterm.setText("0");
        socialMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        socialMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(socialMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 40, 25));

        jTextField42.setBackground(new java.awt.Color(204, 204, 204));
        jTextField42.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField42.setText("0");
        jPanel2.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 40, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField5.setText("Click Select");
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField5.setEnabled(false);
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 254, -1));

        jTextField18.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField18.setText("0");
        jTextField18.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField18.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 40, 25));

        fineartMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        fineartMidterm.setText("0");
        fineartMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        fineartMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(fineartMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 40, 25));

        jTextField43.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField43.setText("0");
        jPanel2.add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 40, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField6.setText("Click Select");
        jTextField6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 254, -1));

        jTextField19.setBackground(new java.awt.Color(204, 204, 204));
        jTextField19.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField19.setText("0");
        jTextField19.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField19.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 40, 25));

        agricMidterm.setBackground(new java.awt.Color(204, 204, 204));
        agricMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        agricMidterm.setText("0");
        agricMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        agricMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        agricMidterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agricMidtermActionPerformed(evt);
            }
        });
        jPanel2.add(agricMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 40, 25));

        jTextField44.setBackground(new java.awt.Color(204, 204, 204));
        jTextField44.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField44.setText("0"); // NOI18N
        jPanel2.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 40, -1));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField7.setText("Click Select");
        jTextField7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField7.setEnabled(false);
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 254, -1));

        jTextField20.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField20.setText("0");
        jTextField20.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField20.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 40, 25));

        crsMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        crsMidterm.setText("0");
        crsMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        crsMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(crsMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 40, 25));

        jTextField45.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField45.setText("0");
        jTextField45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField45ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 40, -1));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField8.setText("Click Select");
        jTextField8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField8.setEnabled(false);
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 254, -1));

        jTextField22.setBackground(new java.awt.Color(204, 204, 204));
        jTextField22.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField22.setText("0");
        jTextField22.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField22.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 40, 25));

        pheMidterm.setBackground(new java.awt.Color(204, 204, 204));
        pheMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pheMidterm.setText("0");
        pheMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        pheMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(pheMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 40, 25));

        jTextField46.setBackground(new java.awt.Color(204, 204, 204));
        jTextField46.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField46.setText("0");
        jPanel2.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 40, -1));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField9.setText("Click Select");
        jTextField9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField9.setEnabled(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 254, -1));

        jTextField21.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField21.setText("0");
        jTextField21.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField21.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 40, 25));

        introtechMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        introtechMidterm.setText("0");
        introtechMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        introtechMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(introtechMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 40, 25));

        jTextField47.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField47.setText("0");
        jPanel2.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 40, -1));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(204, 204, 204));
        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField10.setText("Click Select");
        jTextField10.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField10.setEnabled(false);
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 254, -1));

        jTextField23.setBackground(new java.awt.Color(204, 204, 204));
        jTextField23.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField23.setText("0");
        jTextField23.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField23.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 40, 25));

        homeeconsMidterm.setBackground(new java.awt.Color(204, 204, 204));
        homeeconsMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        homeeconsMidterm.setText("0");
        homeeconsMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        homeeconsMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(homeeconsMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 40, 25));

        jTextField48.setBackground(new java.awt.Color(204, 204, 204));
        jTextField48.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField48.setText("0");
        jPanel2.add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 40, -1));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField11.setText("Click Select");
        jTextField11.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField11.setEnabled(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 254, -1));

        jTextField24.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField24.setText("0");
        jTextField24.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField24.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 40, 25));

        businessMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        businessMidterm.setText("0");
        businessMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        businessMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(businessMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 40, 25));

        jTextField49.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField49.setText("0");
        jPanel2.add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 40, -1));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(204, 204, 204));
        jTextField12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField12.setText("Click Select");
        jTextField12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField12.setEnabled(false);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 254, -1));

        jTextField25.setBackground(new java.awt.Color(204, 204, 204));
        jTextField25.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField25.setText("0");
        jTextField25.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextField25.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 40, 25));

        frenchMidterm.setBackground(new java.awt.Color(204, 204, 204));
        frenchMidterm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        frenchMidterm.setText("0");
        frenchMidterm.setMinimumSize(new java.awt.Dimension(60, 20));
        frenchMidterm.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(frenchMidterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 40, 25));

        jTextField50.setBackground(new java.awt.Color(204, 204, 204));
        jTextField50.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField50.setText("0");
        jPanel2.add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 40, -1));

        jButton2.setText("UPDATE ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 90, 30));

        jButton4.setText("UPDATE");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 80, 30));

        jButton5.setText("UPDATE");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 80, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("CLEAR YOUR ENTRIES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("SUBJECTS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("TEST");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 100, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("MIDTERM");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("EXAM");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Last Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextField38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 173, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("First Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jTextField26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 115, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("INPUT RESULT DATA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 396, 40));

        jDesktopPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 630, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearCounters();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            JOptionPane.showConfirmDialog(this, "Please confirm before you Update your results", "Take Note", JOptionPane.YES_NO_CANCEL_OPTION);

            String sql1 = "UPDATE JSS_TEST SET English = ?,Mathematics = ?, Integrated_Science = ?,Social_Studies = ?,"
            + "Fine_Art = ?, Agricultural_Science = ?, Christian_Religious_Studies = ?, "
            + "Physical_and_Health_Education = ?, "
            + "Introductory_Technology = ?, Home_Economics = ?,"
            + " Business_Studies = ?, French = ? WHERE  student_id = ?";
            con = ConnectionS.connectdb();
            pStmnt = con.prepareStatement(sql1);
            pStmnt.setInt(1, Integer.parseInt(jTextField14.getText()));
            pStmnt.setInt(2, Integer.parseInt(jTextField15.getText()));
            pStmnt.setInt(3, Integer.parseInt(jTextField16.getText()));
            pStmnt.setInt(4, Integer.parseInt(jTextField17.getText()));
            pStmnt.setInt(5, Integer.parseInt(jTextField18.getText()));
            pStmnt.setInt(6, Integer.parseInt(jTextField19.getText()));
            pStmnt.setInt(7, Integer.parseInt(jTextField20.getText()));
            pStmnt.setInt(8, Integer.parseInt(jTextField22.getText()));
            pStmnt.setInt(9, Integer.parseInt(jTextField21.getText()));
            pStmnt.setInt(10, Integer.parseInt(jTextField23.getText()));
            pStmnt.setInt(11, Integer.parseInt(jTextField24.getText()));
            pStmnt.setInt(12, Integer.parseInt(jTextField25.getText()));

            pStmnt.setInt(13, studentId);
            int update = pStmnt.executeUpdate();

            if (update != 0) {

                JOptionPane.showMessageDialog(this, "Update Successful", "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Update Unsuccessful, Try Again", "Take Note", JOptionPane.ERROR_MESSAGE);
            }
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(InputResult.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField45ActionPerformed

    private void agricMidtermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agricMidtermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agricMidtermActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void mathematicsMidtermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathematicsMidtermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathematicsMidtermActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        String lastName = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 1);
        jTextField26.setText(lastName);
        String firstName = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 2);
        jTextField38.setText(firstName);
        studentId = (int) jTable2.getValueAt(jTable2.getSelectedRow(), 0);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        con = ConnectionS.connectdb();
        //Load the Table and Subjects wih the Desired class ID,
        //This implementation can be achieved by declaring a method.
        if (((String) jComboBox1.getSelectedItem()).equals("JSS1")) {
            try {
                sql = "select subjects from class where class_id = 1";
                sql2 = "select student_id, last_name, first_name, middle_name from students_details where class_id =1";
                con = ConnectionS.connectdb();
                stmnt = con.createStatement();
                stmnt.execute(sql);
                subjects = stmnt.getResultSet().getString(1).split(",");

                jTextField1.setText(subjects[0]);
                jTextField2.setText(subjects[1]);
                jTextField3.setText(subjects[2]);
                jTextField4.setText(subjects[3]);
                jTextField5.setText(subjects[4]);
                jTextField6.setText(subjects[5]);
                jTextField7.setText(subjects[6]);
                jTextField8.setText(subjects[7]);
                jTextField9.setText(subjects[8]);
                jTextField10.setText(subjects[9]);
                jTextField11.setText(subjects[10]);
                jTextField12.setText(subjects[11]);
                con.close();
                con = ConnectionS.connectdb();
                stmnt = null;
                stmnt = con.createStatement();
                stmnt.execute(sql2);
                TableModel tm = DbUtils.resultSetToTableModel(stmnt.getResultSet());
                jTable2.setModel(tm);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        if (((String) jComboBox1.getSelectedItem()).equals("JSS2")) {
            try {
                sql = "select subjects from class where class_id = 2";
                sql2 = "select student_id, last_name, first_name, middle_name from students_details where class_id =2";
                con = ConnectionS.connectdb();
                stmnt = con.createStatement();
                stmnt.execute(sql);
                subjects = stmnt.getResultSet().getString(1).split(",");

                jTextField1.setText(subjects[0]);
                jTextField2.setText(subjects[1]);
                jTextField3.setText(subjects[2]);
                jTextField4.setText(subjects[3]);
                jTextField5.setText(subjects[4]);
                jTextField6.setText(subjects[5]);
                jTextField7.setText(subjects[6]);
                jTextField8.setText(subjects[7]);
                jTextField9.setText(subjects[8]);
                jTextField10.setText(subjects[9]);
                jTextField11.setText(subjects[10]);
                jTextField12.setText(subjects[11]);
                con.close();
                con = ConnectionS.connectdb();
                stmnt = null;
                stmnt = con.createStatement();
                stmnt.execute(sql2);
                TableModel tm = DbUtils.resultSetToTableModel(stmnt.getResultSet());
                jTable2.setModel(tm);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

        }
        if (((String) jComboBox1.getSelectedItem()).equals("JSS3")) {
            try {
                sql = "select subjects from class where class_id = 3";
                sql2 = "select student_id, last_name, first_name, middle_name from students_details where class_id =3";
                con = ConnectionS.connectdb();
                stmnt = con.createStatement();
                stmnt.execute(sql);
                subjects = stmnt.getResultSet().getString(1).split(",");

                jTextField1.setText(subjects[0]);
                jTextField2.setText(subjects[1]);
                jTextField3.setText(subjects[2]);
                jTextField4.setText(subjects[3]);
                jTextField5.setText(subjects[4]);
                jTextField6.setText(subjects[5]);
                jTextField7.setText(subjects[6]);
                jTextField8.setText(subjects[7]);
                jTextField9.setText(subjects[8]);
                jTextField10.setText(subjects[9]);
                jTextField11.setText(subjects[10]);
                jTextField12.setText(subjects[11]);
                con.close();
                con = ConnectionS.connectdb();
                stmnt = null;
                stmnt = con.createStatement();
                stmnt.execute(sql2);
                TableModel tm = DbUtils.resultSetToTableModel(stmnt.getResultSet());
                jTable2.setModel(tm);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agricMidterm;
    private javax.swing.JTextField businessMidterm;
    private javax.swing.JTextField crsMidterm;
    private javax.swing.JTextField englishMidterm;
    private javax.swing.JTextField fineartMidterm;
    private javax.swing.JTextField frenchMidterm;
    private javax.swing.JTextField homeeconsMidterm;
    private javax.swing.JTextField introtechMidterm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField mathematicsMidterm;
    private javax.swing.JTextField pheMidterm;
    private javax.swing.JTextField scienceMidterm;
    private javax.swing.JTextField socialMidterm;
    // End of variables declaration//GEN-END:variables
}
